"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { checkRoutes } from '@/functions/checkRoutes'
import PrivateRoutes from '@/components/privateRoutes'
import { UserContextProvider } from '@/context/userContext'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()

  const isPublicRoute = checkRoutes(pathname!)


  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          {isPublicRoute && children}
          {!isPublicRoute && (
            <PrivateRoutes>
              {<Home />}
            </PrivateRoutes>
          )}
        </UserContextProvider>
      </body>
    </html>
  )
}
